version: '2'

services:
  db:
    container_name: db
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: iam
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: iam

    ports:
      - "3306:3306"

  trust:
    build:
      context: ./trust-anchors
    command: /bin/true

  iam-be:
    container_name: iam-be
    image: ${DOCKER_REGISTRY_HOST}/italiangrid/iam-login-service:${IMAGE_TAG}

    build:
      context: ./iam-be

    environment:
      IAM_JAVA_OPTS: -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1044 -Dspring.profiles.active=mysql-test
      IAM_BASE_URL: https://iam.local.io
      IAM_ISSUER: https://iam.local.io
      IAM_USE_FORWARDED_HEADERS: "true"

      IAM_DB_HOST: db
      IAM_DB_USERNAME: iam
      IAM_DB_PASSWORD: pwd

      IAM_GOOGLE_CLIENT_ID: ${IAM_GOOGLE_CLIENT_ID}
      IAM_GOOGLE_CLIENT_SECRET: ${IAM_GOOGLE_CLIENT_SECRET}
      IAM_GOOGLE_CLIENT_REDIRECT_URIS: https://iam.local.io/openid_connect_login

      IAM_GITHUB_CLIENT_ID: ${IAM_GITHUB_CLIENT_ID}
      IAM_GITHUB_CLIENT_SECRET: ${IAM_GITHUB_CLIENT_SECRET}

      IAM_SAML_IDP_METADATA: file:///srv/indigo-iam/saml-idp/idp/shibboleth-idp/metadata/idp-metadata.xml
      IAM_SAML_ENTITY_ID: urn:iam:iam-devel
      IAM_NOTIFICATION_DISABLE: "true"

    ports:
      - "1044:1044"

    volumes_from:
      - trust

  iam:
    build:
      context: ./nginx/

    depends_on:
      - iam-be

    dns_search: local.io

    container_name: iam

    environment:
      NGINX_HOST: iam
      NGINX_PORT: 443

    ports:
      - "443:443"
